app:
  name: 'Kyle-PostgreSQL'
  version: '1.0.0'

database:
  host: 'localhost'
  user: 'kyle'
  password: '1q2w3e4r'
  dbname: 'blockchain'
  port: 5432
  sslmode: 'disable'
  timezone: 'Asia/Seoul'

# dbs
blockchain:
  schema: 'kyle'
  tables:
    - name: 'transactions'
      columns:
        - name: 'hash'
          type: 'VARCHAR(66)'
          primary_key: true
          not_null: true
        - name: 'blockHash'
          type: 'VARCHAR(66)'
        - name: 'blockNumber'
          type: 'VARCHAR(32)'
        - name: 'transactionIndex'
          type: 'VARCHAR(32)'
        - name: 'chainId'
          type: 'VARCHAR(32)'
        - name: 'type'
          type: 'VARCHAR(32)'
        - name: 'from'
          type: 'VARCHAR(42)'
        - name: 'to'
          type: 'VARCHAR(42)'
        - name: 'value'
          type: 'VARCHAR(64)'
        - name: 'gas'
          type: 'VARCHAR(32)'
        - name: 'gasPrice'
          type: 'VARCHAR(64)'
        - name: 'maxFeePerGas'
          type: 'VARCHAR(64)'
        - name: 'maxPriorityFeePerGas'
          type: 'VARCHAR(64)'
        - name: 'input'
          type: 'TEXT'
        - name: 'nonce'
          type: 'VARCHAR(32)'
        - name: 'r'
          type: 'VARCHAR(66)'
        - name: 's'
          type: 'VARCHAR(66)'
        - name: 'v'
          type: 'VARCHAR(10)'
        - name: 'yParity'
          type: 'VARCHAR(10)'
        - name: 'accessList'
          type: 'JSONB'

    - name: 'transaction_receipts'
      columns:
        - name: 'transactionHash'
          type: 'VARCHAR(66)'
          primary_key: true
          not_null: true
        - name: 'transactionIndex'
          type: 'VARCHAR(32)'
        - name: 'type'
          type: 'VARCHAR(32)'
        - name: 'status'
          type: 'VARCHAR(32)'
        - name: 'blockHash'
          type: 'VARCHAR(66)'
        - name: 'blockNumber'
          type: 'VARCHAR(32)'
        - name: 'cumulativeGasUsed'
          type: 'VARCHAR(64)'
        - name: 'effectiveGasPrice'
          type: 'VARCHAR(64)'
        - name: 'gasUsed'
          type: 'VARCHAR(64)'
        - name: 'from'
          type: 'VARCHAR(42)'
        - name: 'to'
          type: 'VARCHAR(42)'
        - name: 'contractAddress'
          type: 'VARCHAR(42)'
        - name: 'logsBloom'
          type: 'TEXT'
      foreign_keys:
        - column: 'transactionHash'
          references:
            table: 'transactions'
            column: 'hash'

    - name: 'logs'
      columns:
        - name: 'id'
          type: 'SERIAL'
          primary_key: true
        - name: 'address'
          type: 'VARCHAR(42)'
        - name: 'blockHash'
          type: 'VARCHAR(66)'
        - name: 'blockNumber'
          type: 'VARCHAR(32)'
        - name: 'data'
          type: 'TEXT'
        - name: 'topics'
          type: 'JSONB'
        - name: 'logIndex'
          type: 'VARCHAR(32)'
        - name: 'removed'
          type: 'BOOLEAN'
        - name: 'transactionHash'
          type: 'VARCHAR(66)'
          index: true
        - name: 'transactionIndex'
          type: 'VARCHAR(32)'
      foreign_keys:
        - column: 'transactionHash'
          references:
            table: 'transactions'
            column: 'hash'
